### ISSUE TITLE
This plugin need a version tag

### ISSUE THREAD

**Issue by buzzworkers** [phergie/phergie-irc-plugin-react-twitter#1]
currently unable to use composer.json like this with this plugin

 {
    "minimum-stability": "dev",
    "require": {
        "phergie/phergie-irc-bot-react":  "~1",
		"phergie/phergie-irc-plugin-react-pong": "~1",
		"phergie/phergie-irc-plugin-react-feedticker": "~1",
		"phergie/phergie-irc-plugin-react-commandhelp": "~1",
		"chrismou/phergie-irc-plugin-react-google": "~1",
		"chrismou/phergie-irc-plugin-react-audioscrobbler": "~1",
		"phergie/phergie-irc-plugin-react-nickserv": "~1",
		"phergie/phergie-irc-plugin-react-quit": "~1",
		"phergie/phergie-irc-plugin-react-thefuckingweather": "~1",
		"chrismou/phergie-irc-plugin-react-weather": "~1",
		"phergie/phergie-irc-plugin-react-youtube": "~1",
		"phergie/phergie-irc-plugin-react-autojoin": "~1",
		"phergie/phergie-irc-plugin-react-twitter": "~1",
		"phergie/phergie-irc-plugin-react-joinpart": "~1"
    }
}

output this : 

  Problem 4
    - The requested package phergie/phergie-irc-plugin-react-twitter could not be found in any version, there may be a typo in the package name.

**Comment by elazar** [comment]
This plugin also needs tests, unfortunately. :( That's the primary blocker in making a stable release.

**Comment by svpernova09** [comment]
Closed via https://github.com/phergie/phergie-irc-plugin-react-twitter/releases/tag/1.0.0
